name: uzhindoma
description: Uzhin Doma App

version: 1.0.23+23000

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # surf
  surf_lint_rules: 0.0.2-dev.2
  surf_logger: 0.0.1-dev.6
  surf_mwwm: 0.0.1-dev.9
  mwwm: 0.1.3-dev.9
  surf_util: 0.0.1-dev.9
  bottom_sheet: 0.0.1-dev.7
  swipe_refresh: 0.0.1-dev.12
  analytics: 0.0.1-dev.2

  # firebase
  firebase_core: 1.22.0
  firebase_core_platform_interface: 4.5.1
  firebase_crashlytics: ^2.8.10
  firebase_analytics: ^9.3.5
  #  firebase_dynamic_links: 0.6.3
  #  firebase_performance: 0.4.3
  firebase_messaging: ^13.0.3

  # appmetrica
  appmetrica_plugin: ^1.0.1
  appmetrica_push_plugin: ^0.2.0
#  appmetrica_push: ^1.0.0

  # svg, icons, asset helper
  flutter_svg: 0.23.0
  cupertino_icons: 1.0.0
  transparent_image: 1.0.0

  # network
  http: 0.13.1
  dio: 4.0.0
  retrofit: ^2.0.0
  uni_links: ^0.5.1


  package_info_plus: ^1.4.2

#  flutter_cupertino_date_picker: ^1.0.26+2
  flutter_cupertino_date_picker:
    path: ./packages/flutter-cupertino-date-picker

  # storage
  shared_preferences: 2.0.6

  # rx (24 потому что mwwm тянет именно его)
  rxdart: 0.24.0

  # common
  path_provider: 2.0.2
  url_launcher: ^6.1.5          #6.0.1  5.7.10
  shimmer: 1.1.2
  scrollable_positioned_list: ^0.1.9
  intl: ^0.17.0     #0.17.0   0.16.1
  crypt: ^4.2.1
  device_info: ^2.0.1
  flutter_secure_storage: ^3.3.5
  permission_handler: ^10.0.0
  geolocator: ^9.0.1
  webview_flutter: ^3.0.2
  render_metrics: 1.0.2-dev.9
  loading_indicator: 1.2.0
  dotted_line: ^2.0.2
  fluttertoast: ^7.0.0
  share_plus: ^2.0.2         #2.0.2  1.2.0
  mad_pay:
    path: ./packages/mad_pay
  wakelock: ^0.5.0
  carousel_slider: ^4.1.1
  clipboard: ^0.1.3

dev_dependencies:
  # Команда - flutter pub run flutter_launcher_icons:main -f flutter_launcher_icons.yaml
  flutter_launcher_icons: ^0.9.0
  # Команда - flutter pub pub run flutter_native_splash:create
  flutter_native_splash: ^1.1.0
  # use analysis_option.yaml
  pedantic: ^1.11.1
  # кодген для ретрофита
  retrofit_generator: ^2.0.0+1
  # билдер для кодгена - flutter pub run build_runner build
  build_runner: ^2.0.4
  # для генерации json
  json_serializable: ^4.1.1

  # тестирование
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - res/assets/
    - res/assets/icons/
    - res/assets/splash/
    - res/assets/onboarding/

  fonts:
    - family: Rubik
      fonts:
        - asset: res/assets/fonts/Rubik-Light.ttf
          weight: 300
        - asset: res/assets/fonts/Rubik-Regular.ttf
          weight: 400
        - asset: res/assets/fonts/Rubik-Medium.ttf
          weight: 500
        - asset: res/assets/fonts/Rubik-SemiBold.ttf
          weight: 700
