-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQg8IjyPVeqlezvZ1/7
eWEuGqWtPqd4lwTmkzqCtU64ybSgCgYIKoZIzj0DAQehRANCAARQcrGZl/DN39t5
tM4XjQyLeRS/FMMAj6+Lrufc0MHv+QpbPHSEBqm3pt18wzeRwueK+ZjjEDjMy9Xe
PeA/JbMk
-----END PRIVATE KEY-----